# Generated by Django 4.2.6 on 2023-10-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0003_auto_20231030_1039'),
        ('SurveyApp', '0014_alter_question_option_a_alter_question_option_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='unidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso'),
            preserve_default=False,
        ),
    ]
