# Generated by Django 4.2.6 on 2023-11-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0004_remove_pregunta_opciones_respuesta_and_more'),
        ('SurveyApp', '0015_question_curso_question_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='question',
            name='unidad',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SurveyApp.question')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answers', models.ManyToManyField(to='SurveyApp.answer')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SurveyApp.contenido')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso')),
                ('questions', models.ManyToManyField(to='SurveyApp.question')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
            ],
        ),
    ]
