# Generated by Django 4.2.6 on 2023-11-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0016_remove_question_curso_remove_question_unidad_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SurveyApp.quiz'),
        ),
    ]
