# Generated by Django 4.2.6 on 2023-11-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0018_alter_question_correct_answer_alter_question_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='contenido',
            new_name='texto',
        ),
    ]
