# Generated by Django 4.2.6 on 2023-11-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0019_rename_contenido_contenido_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='titulo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
