# Generated by Django 4.2.6 on 2023-11-07 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0020_video_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='questions',
            new_name='preguntas',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='contenido',
        ),
        migrations.AddField(
            model_name='actividad',
            name='contenidos',
            field=models.ManyToManyField(to='SurveyApp.contenido'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SurveyApp.quiz'),
        ),
    ]
