# Generated by Django 4.2.6 on 2023-11-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0021_rename_questions_actividad_preguntas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='contenidos',
            field=models.ManyToManyField(null=True, to='SurveyApp.contenido'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='preguntas',
            field=models.ManyToManyField(null=True, to='SurveyApp.question'),
        ),
    ]
