# Generated by Django 4.2.6 on 2023-11-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0003_auto_20231030_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='opciones_respuesta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta_correcta',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='preguntas',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='video',
            name='unidad',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='OpcionRespuesta',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Quizz',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
